services:
  - type: web
    name: portfolio-website
    env: node
    region: ohio
    plan: free
    branch: main
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
