services:
  - type: web
    name: portfolio-website
    env: node
    region: ohio
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_ENV
        value: production
